# Generated by Django 5.2 on 2025-05-20 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_rename_workers_course_students'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='students',
            new_name='workers',
        ),
    ]
